server:
  port: 8080

spring:
  messages:
    basename: i18n.login

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

mybatis:
  type-aliases-package: com.zzl.myblog.entity
  mapper-locations: classpath:mapper/*.xml



